/** Caminhos das páginas públicas de conteúdo (PUL-242). Um lugar só, para `related` e rodapé não digitarem string. */
export const SLUG = {
  PSA: '/o-que-e-psa',
  MARGEM_REALIZADA: '/o-que-e-margem-realizada',
  MARGEM: '/controle-de-margem-por-projeto',
  CUSTO_HORA: '/custo-hora-de-funcionario',
  VALOR_HORA: '/valor-hora-de-venda-de-servicos',
  ALOCACAO: '/alocacao-de-equipe-em-projetos',
  CONTROLE_HORAS: '/controle-de-horas-por-projeto',
  ORCAMENTO: '/orcamento-de-projeto-com-margem',
  CONSULTORIAS: '/software-de-gestao-para-consultorias',
  AGENCIAS: '/software-para-agencias',
  SOFTWARE_HOUSE: '/psa-para-software-house',
  ARQUITETURA: '/gestao-de-projetos-para-escritorio-de-arquitetura',
  ENGENHARIA: '/software-para-escritorio-de-engenharia',
  HORAS_UTEIS: '/horas-uteis-por-mes',
  SCOPE_CREEP: '/o-que-e-scope-creep',
  PRECIFICAR_SOFTWARE: '/como-precificar-projeto-de-software',
  REAJUSTE: '/reajuste-de-contrato-de-prestacao-de-servicos',
  VARIOS_PROJETOS: '/gerenciar-varios-projetos-ao-mesmo-tempo',
} as const;
