project_id = "vkriobpmolgopbbpqeky"

[functions.send-invite-email]
verify_jwt = false

[functions.create-employee-user]
verify_jwt = false

[functions.seed-admin]
verify_jwt = false

[functions.register-tenant]
verify_jwt = false

[functions.recalculate-employee-costs]
verify_jwt = false

[functions.resend-employee-invite]
verify_jwt = false

[functions.parse-cnpj-card]
verify_jwt = false
